### ISSUE TITLE
Including LICENSE file in the code repository and Adding it in the Manifest file

### ISSUE THREAD

**Issue by chkumar246** [cdent/wsgi-intercept#33]
I am packaging wsgi-intercept python module for fedora.
As per setup.py file, License is MIT. But License file is missing from the code repository.
Please include it.

**Comment by cdent** [comment]
Thanks for the heads up. Let me know if the change in 209c23b is insufficient.

**Comment by chkumar246** [comment]
Thanks @cdent . It will fix the issue.
Can you do a release bump so that the latest tarball to 0.10.3gets updated on pypi?

**Comment by cdent** [comment]
Was just waiting on some testing and review, will add the title and do a release.

**Comment by cdent** [comment]
0.10.3 is now released

next time feel free to make a pull request
