### ISSUE TITLE
Please allow to disable internet tests

### ISSUE THREAD

**Issue by thomasgoirand** [cdent/wsgi-intercept#36]
When building the package in Debian, I had to patch out all tests doing external network connections (to google.com in this case), because buildd do not have network access (on purpose). The issue is that on each new upstream release, the patch to remove these tests must be rebased, which is annoying.

It'd be nice to have an option set through environment variable to disable these tests when running pytest. Something like this:
WSGI_INTERCEPT_DO_NOT_TEST_WITH_INTERNET=yes

**Comment by thomasgoirand** [comment]
With a 2nd though, what should be checked is if we have:
export http_proxy=127.0.0.1:9
export https_proxy=127.0.0.1:9

which is what is done in Debian for python packages to make sure we always have no network. wsgi-intercept could check the content of this variable, and if it is 127.0.0.1:9, then it means there's no network available.

**Comment by cdent** [comment]
I'd rather use something more generic, especially since 905ef41cb0455a9dc3e20a64ff71c2c289b557bf isn't happy when http_proxy is in the environment.

Using a more general variable will be explicit.

**Comment by cdent** [comment]
@thomasgoirand if you could review the linked commit to see if it does what you need, that would be great.
