### ISSUE TITLE
wsgi_intercept.make_environ turns headers into unicode

### ISSUE THREAD

**Issue by socek** [cdent/wsgi-intercept#39]
[wsgi-intercept==1.2.2]
I'm using requests.Session() -> wsgi_intecept -> falcon
I'm trying to use cookies, but I can not. wsgi_intercept.make_environ method turns headers into unicode, and this is not working with SimpleCookie.load:

```
def load(self, rawdata):
    if type(rawdata) == type(""):
        self.__ParseString(rawdata)
    else:
        # self.update() wouldn't call our custom __setitem__
        for k, v in rawdata.items():
            self[k] = v
    return
```

As you can see, the SimpleCookie check if rawdata is type of "", which is not when the rawdata is an unicode, and this result in error: AttributeError: 'unicode' object has no attribute 'items'

The simplest way to "fix" this is to remove line https://github.com/cdent/wsgi-intercept/blob/master/wsgi_intercept/__init__.py#L223 but this line is there for a reason and I do not know why.

**Comment by cdent** [comment]
@socek If you could check the current master to see if it fixes your problem that would be great. If it does (and doesn't break other stuff) I'll make a new release with the fix from e3ef80c.

Thanks very much for reporting the issue. Getting [str stuff right in wsgi headers is a huge pain](https://mail.python.org/pipermail/web-sig/2012-October/005204.html).

**Comment by socek** [comment]
Great!
It works like a charm. My tests return success, so this issue is fixed.
Thanks a lot!

**Comment by cdent** [comment]
https://pypi.python.org/pypi/wsgi_intercept has 1.3.0 now
