### ISSUE TITLE
Pypi sdist tarball doesn't have README.rst

### ISSUE THREAD

**Issue by dvzrv** [cdent/wsgi-intercept#55]
Hi!
It would be great to also have README.rst in the pypi sdist tarball, as for consistency I'm using that upstream, when packaging for Arch Linux.
Thanks!

**Comment by cdent** [comment]
Thanks for catching this. Will fix ASAP.

**Comment by cdent** [comment]
Actually, the `README` is there, which is the same content (one is a symlink of the other). Is that not sufficient?

**Comment by dvzrv** [comment]
@cdent: Oh, my bad. I can use `README` then! Thanks! :)
