### ISSUE TITLE
Incompatibility with pytest 7.2.0

### ISSUE THREAD

**Issue by frenzymadness** [cdent/wsgi-intercept#68]
Hello. pytest 7.2.0 no longer depends on py so lines like this one

https://github.com/cdent/wsgi-intercept/blob/4349a59fe8dcbbb0ba39087741295926df483d24/wsgi_intercept/tests/test_interceptor.py#L10

no longer works with pytest 7.2.0.

**Comment by cdent** [comment]
Thanks for the heads up, I've started a fix with #69.

When that's merged I'll release a new version to pypi.

**Comment by cdent** [comment]
https://pypi.org/project/wsgi-intercept/
